default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: car_garage_development

test:
  <<: *default
  database: car_garage_test

production:
  <<: *default
  database: car_garage_production
  username: car_garage
  password: <%= ENV["CAR_GARAGE_DATABASE_PASSWORD"] %>
